site_name: Advanced Higher Computing Science
nav:
    - Home: 'index.md'
    - Unit 1 - Software Design and Development:
      - SDD/index.md
      - Analysis: 
          - Functional Requirements: 'SDD/1.2-Functional-Requirements.md'
          - Feasability Studies: 'SDD/1.3-Feasability-Studies.md'
          - Project Planning: 'SDD/1.4-Project-Planning.md'
          - Requirement Specification: 'SDD/1.5-Requirement-Specification.md'  
     # - Design:
          #- Functional Requirements: ''
      - Implementation - Data Types and Structures:
          - Parallel-1D-arrays: 'SI/1.1-Parallel-1D-Arrays.md'  
          - Working-with-Records: 'SI/1.2-Working-with-Records.md' 
          - Arrays-of-Records: 'SI/1.3-Arrays-of-Records.md' 
      - Implementation - Algorithm specification:
          - Insertation Sorts: 'SI/3.2-Insertation-Sorts.md'
          - Binary Search: 'SI/3.4-Binary-Search.md'
    - Unit 2 - Computer Systems:
      - CS/index.md
    - Unit 3 - Database Design and Development:
      - DDD/index.md
      
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
theme:
  name: material
  font:
    text: Quicksand
  palette: 
    - scheme: slate
      toggle:
       icon: material/weather-sunny
       name: Dark mode
      primary: green
      accent: deep purple

    - scheme: default
      toggle:
       icon: material/weather-night
       name: Light mode
      primary: blue
      accent: deep orange
  icon:
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left
  features:
    - content.code.copy
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.indexes 
    - navigation.expand
